{
    'name': 'webtask',
    'version': '12.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'webtask',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Byte',
    'maintainer': 'Byte',
    'website': 'bytelegions.com',
    'depends': ['website'],
    'demo': [],
    'data': [
        'data/sequence.xml',
        'views/template.xml',
        'views/patient.xml',
        'views/doctor.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
